name: 💡 Feature Request
description: Suggest an idea or improvement for Cryo
title: "[Idea]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: Describe the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
      description: What problem does it solve for you?
